/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWardrobeIndexRouteImport } from './routes/_authenticated/wardrobe/index'
import { Route as AuthenticatedOutfitsIndexRouteImport } from './routes/_authenticated/outfits/index'
import { Route as AuthenticatedWardrobeItemIdRouteImport } from './routes/_authenticated/wardrobe/$itemId'
import { Route as AuthenticatedOutfitsOutfitIdRouteImport } from './routes/_authenticated/outfits/$outfitId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWardrobeIndexRoute =
  AuthenticatedWardrobeIndexRouteImport.update({
    id: '/wardrobe/',
    path: '/wardrobe/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutfitsIndexRoute =
  AuthenticatedOutfitsIndexRouteImport.update({
    id: '/outfits/',
    path: '/outfits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWardrobeItemIdRoute =
  AuthenticatedWardrobeItemIdRouteImport.update({
    id: '/wardrobe/$itemId',
    path: '/wardrobe/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutfitsOutfitIdRoute =
  AuthenticatedOutfitsOutfitIdRouteImport.update({
    id: '/outfits/$outfitId',
    path: '/outfits/$outfitId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/outfits/$outfitId': typeof AuthenticatedOutfitsOutfitIdRoute
  '/wardrobe/$itemId': typeof AuthenticatedWardrobeItemIdRoute
  '/outfits/': typeof AuthenticatedOutfitsIndexRoute
  '/wardrobe/': typeof AuthenticatedWardrobeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/outfits/$outfitId': typeof AuthenticatedOutfitsOutfitIdRoute
  '/wardrobe/$itemId': typeof AuthenticatedWardrobeItemIdRoute
  '/outfits': typeof AuthenticatedOutfitsIndexRoute
  '/wardrobe': typeof AuthenticatedWardrobeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_authenticated/outfits/$outfitId': typeof AuthenticatedOutfitsOutfitIdRoute
  '/_authenticated/wardrobe/$itemId': typeof AuthenticatedWardrobeItemIdRoute
  '/_authenticated/outfits/': typeof AuthenticatedOutfitsIndexRoute
  '/_authenticated/wardrobe/': typeof AuthenticatedWardrobeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/outfits/$outfitId'
    | '/wardrobe/$itemId'
    | '/outfits/'
    | '/wardrobe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/outfits/$outfitId'
    | '/wardrobe/$itemId'
    | '/outfits'
    | '/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/signup'
    | '/_authenticated/outfits/$outfitId'
    | '/_authenticated/wardrobe/$itemId'
    | '/_authenticated/outfits/'
    | '/_authenticated/wardrobe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wardrobe/': {
      id: '/_authenticated/wardrobe/'
      path: '/wardrobe'
      fullPath: '/wardrobe/'
      preLoaderRoute: typeof AuthenticatedWardrobeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outfits/': {
      id: '/_authenticated/outfits/'
      path: '/outfits'
      fullPath: '/outfits/'
      preLoaderRoute: typeof AuthenticatedOutfitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wardrobe/$itemId': {
      id: '/_authenticated/wardrobe/$itemId'
      path: '/wardrobe/$itemId'
      fullPath: '/wardrobe/$itemId'
      preLoaderRoute: typeof AuthenticatedWardrobeItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outfits/$outfitId': {
      id: '/_authenticated/outfits/$outfitId'
      path: '/outfits/$outfitId'
      fullPath: '/outfits/$outfitId'
      preLoaderRoute: typeof AuthenticatedOutfitsOutfitIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedOutfitsOutfitIdRoute: typeof AuthenticatedOutfitsOutfitIdRoute
  AuthenticatedWardrobeItemIdRoute: typeof AuthenticatedWardrobeItemIdRoute
  AuthenticatedOutfitsIndexRoute: typeof AuthenticatedOutfitsIndexRoute
  AuthenticatedWardrobeIndexRoute: typeof AuthenticatedWardrobeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedOutfitsOutfitIdRoute: AuthenticatedOutfitsOutfitIdRoute,
  AuthenticatedWardrobeItemIdRoute: AuthenticatedWardrobeItemIdRoute,
  AuthenticatedOutfitsIndexRoute: AuthenticatedOutfitsIndexRoute,
  AuthenticatedWardrobeIndexRoute: AuthenticatedWardrobeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
